### ISSUE TITLE
I can't use this app. I don't know why I am getting an error  

### ISSUE THREAD

**Issue by bhuvanrtz** [Rahuletto/lirics#1]

**Comment by bhuvanrtz** [comment]
https://github.com/user-attachments/assets/efdef6cd-fc42-4db7-b31a-024526caebca

**Comment by Rahuletto** [comment]
Because as the `README.md` mentioned,
> Lirics is a self-hosting service that brings real-time Spotify lyrics to your screen with a beautiful, Apple Music-like aesthetic.

and

> This can only be self-hosted as Spotify didnt approve my application for the API to be used by public
